name: dbt_snowflake_demo
version: 1.0
config-version: 2

profile: dbt_snowflake_demo

model-paths: ["models"]

models:
  dbt_snowflake_demo:
    staging:
      +schema: staging
    marts:
      +schema: marts
